[package]
name = "gstsmith-compose-app"
description = "GStreamer application composed from a gstsmith-app PipelineBin."
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
anyhow = { workspace = true }
gstsmith-app = { path = "../.." }
tokio = { workspace = true, features = ["rt-multi-thread", "signal"] }

[lints]
workspace = true
